services:
    psql_bp:
        image: postgres:18-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${APSCHOOL_DB_DATABASE}
            POSTGRES_USER: ${APSCHOOL_DB_USERNAME}
            POSTGRES_PASSWORD: ${APSCHOOL_DB_PASSWORD}
        ports:
            - "${APSCHOOL_DB_PORT}:5432"
        volumes:
            - psql_volume_bp:/var/lib/postgresql/data

volumes:
    psql_volume_bp:
